import re

_PATTERNS = {
    'TASK': re.compile(r'^\s*TASK\s+\"([^\"]+)\"(?:\s*\{\s*)?$'),
    'STEP': re.compile(r'^\s*STEP\s+\"([^\"]+)\"\s*\{\s*$'),
    'SETUP': re.compile(r'^\s*SETUP\s+\"([^\"]+)\"\s*\{\s*$'),
    'PARALLEL': re.compile(r'^\s*PARALLEL\s*\{\s*$'),
    'CHOOSE': re.compile(r'^\s*CHOOSE\s*\{\s*$'),
    'OPTION': re.compile(r'^\s*OPTION\s+\"([^\"]+)\"\s*\{\s*$'),
    'ESTIMATE_COST': re.compile(r'^\s*ESTIMATE_COST\s*\{\s*$'),
    'BLOCK_END': re.compile(r'^\s*\}\s*$'),
    'RUN': re.compile(r'^\s*RUN\s+([\\'\"])(.*?)\\1\s*$'),
    'LOG': re.compile(r'^\s*LOG\s+([\\'\"])(.*?)\\1\s*$'),
    'WRITE': re.compile(r'^\s*WRITE\s+\"([^\"]+)\"\s+<<(\w+)\s*$'),
    'ASSERT': re.compile(r'^\s*ASSERT\s+(.+?)\s*$'),
    'READ': re.compile(r'^\s*READ\s+\"([^\"]+)\"\s+AS\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*$'),
    'PROMPT_AGENT': re.compile(r'^\s*PROMPT_AGENT\s+\"([^\"]+)\"(?:\s+INTO\s+([a-zA-Z_][a-zA-Z0-9_]*))?\s*$'),
    'SET_BUDGET': re.compile(r'^\s*SET_BUDGET\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+?)\s*$'),
    'REQUEST_REVIEW': re.compile(r'^\s*REQUEST_REVIEW\s+\"([^\"]+)\"\s*$'),
    'PAUSE': re.compile(r'^\s*PAUSE\s+\"([^\"]+)\"\s*$'),
    'IF': re.compile(r'^\s*IF\s+(.+?)\s+THEN\s*\{\s*$'),
    'ELSE': re.compile(r'^\s*ELSE\s*\{\s*$'),
    'COMPARATOR': re.compile(r'(==|!=|<|>|<=|>=)'),
    'BOOLEAN': re.compile(r'^(true|false)$'),
    'DIRECTIVE': re.compile(r'^\s*@([a-zA-Z_][a-zA-Z0-9_]*)\s+(.+?)\s*$'),
    'COMMENT': re.compile(r'^\s*#.*\n?'),
    'EMPTY': re.compile(r'^\s*\n?$'),
}