openapi: 3.0.3
info:
  title: TissDB Business Intelligence Service API
  description: API for managing reports and alerts within the TissDB BI Suite.
  version: 1.0.0
servers:
  - url: http://tissdb.internal:8080/
    description: Internal Development Server

paths:
  /_health:
    get:
      summary: Health Check
      tags: [System]
      operationId: healthCheck
      responses:
        '200':
          description: Server is healthy.
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  /_collections:
    get:
      summary: List all collections
      tags: [System]
      operationId: listCollections
      responses:
        '200':
          description: A list of collection names.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["users", "products"]
  /_begin:
    post:
      summary: Begin Transaction
      tags: [Transactions]
      operationId: beginTransaction
      responses:
        '200':
          description: Transaction started successfully.
  /_commit:
    post:
      summary: Commit Transaction
      tags: [Transactions]
      operationId: commitTransaction
      responses:
        '200':
          description: Transaction committed successfully.
  /_rollback:
    post:
      summary: Rollback Transaction
      tags: [Transactions]
      operationId: rollbackTransaction
      responses:
        '200':
          description: Transaction rolled back successfully.
  /_bi/dashboards:
    post:
      summary: Create a new dashboard configuration
      tags: [BI]
      operationId: createDashboard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          description: Dashboard created successfully.
  /_bi/dashboards/{dashboardId}:
    get:
      summary: Get a specific dashboard configuration by ID
      tags: [BI]
      operationId: getDashboardById
      parameters:
        - name: dashboardId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The dashboard configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Dashboard not found.
    put:
      summary: Update a specific dashboard configuration
      tags: [BI]
      operationId: updateDashboard
      parameters:
        - name: dashboardId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Dashboard updated successfully.
        '404':
          description: Dashboard not found.
  /{collection}:
    put:
      summary: Create a new collection
      tags: [Collections]
      operationId: createCollection
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Collection created.
    delete:
      summary: Delete a collection
      tags: [Collections]
      operationId: deleteCollection
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Collection deleted.
    post:
      summary: Create a new document in a collection
      tags: [Documents]
      operationId: createDocument
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          description: Document created.
  /{collection}/{id}:
    get:
      summary: Get a document by ID
      tags: [Documents]
      operationId: getDocumentById
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The document.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found.
    put:
      summary: Create or update a document by ID (upsert)
      tags: [Documents]
      operationId: upsertDocument
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Document updated.
    delete:
      summary: Delete a document by ID
      tags: [Documents]
      operationId: deleteDocument
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Document deleted.
  /{collection}/_schema:
    put:
      summary: Set collection schema
      tags: [Collections]
      operationId: setSchema
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schema'
      responses:
        '200':
          description: Schema updated.
  /{collection}/_query:
    post:
      summary: Execute a TissQL query
      tags: [Documents]
      operationId: executeQuery
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "SELECT id, name FROM users WHERE age > 30"
      responses:
        '200':
          description: Query results.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
  /{collection}/_index:
    post:
      summary: Create an index
      tags: [Collections]
      operationId: createIndex
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                field:
                  type: string
                  example: "user_id"
      responses:
        '200':
          description: Index created.

  /_bi/reports:
    get:
      summary: List all report configurations
      tags: [Reports]
      operationId: listReports
      responses:
        '200':
          description: A list of report configurations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
    post:
      summary: Create a new report configuration
      tags: [Reports]
      operationId: createReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportInput'
      responses:
        '201':
          description: Report created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /_bi/reports/{reportId}:
    get:
      summary: Get a specific report configuration by ID
      tags: [Reports]
      operationId: getReportById
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The report configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a specific report configuration
      tags: [Reports]
      operationId: updateReport
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportInput'
      responses:
        '200':
          description: Report updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found.
        '400':
          description: Invalid input.
    delete:
      summary: Delete a specific report configuration
      tags: [Reports]
      operationId: deleteReport
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Report deleted successfully.
        '404':
          description: Report not found.

  /_bi/alerts:
    get:
      summary: List all alert configurations
      tags: [Alerts]
      operationId: listAlerts
      responses:
        '200':
          description: A list of alert configurations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alert'
    post:
      summary: Create a new alert configuration
      tags: [Alerts]
      operationId: createAlert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertInput'
      responses:
        '201':
          description: Alert created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '400':
          description: Invalid input.

  /_bi/alerts/{alertId}:
    get:
      summary: Get a specific alert configuration by ID
      tags: [Alerts]
      operationId: getAlertById
      parameters:
        - name: alertId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The alert configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '404':
          description: Alert not found.
    put:
      summary: Update a specific alert configuration
      tags: [Alerts]
      operationId: updateAlert
      parameters:
        - name: alertId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertInput'
      responses:
        '200':
          description: Alert updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '404':
          description: Alert not found.
    delete:
      summary: Delete a specific alert configuration
      tags: [Alerts]
      operationId: deleteAlert
      parameters:
        - name: alertId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Alert deleted successfully.
        '404':
          description: Alert not found.

components:
  schemas:
    ReportInput:
      type: object
      properties:
        name:
          type: string
          example: "Weekly High-Value Orders"
        tissql_query:
          type: string
          example: "SELECT customer_id, order_date, total FROM orders WHERE total > 5000"
        schedule:
          type: string
          description: "Cron syntax for the schedule."
          example: "0 9 * * 1"
        format:
          type: string
          enum: [csv, json, pdf]
          example: "csv"
        channels:
          type: array
          items:
            $ref: '#/components/schemas/Channel'
      required: [name, tissql_query, schedule, format, channels]

    Report:
      allOf:
        - $ref: '#/components/schemas/ReportInput'
        - type: object
          properties:
            id:
              type: string
              format: uuid
              example: "a1b2c3d4-e5f6-4a3b-8c2d-1e9f8a7b6c5d"
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            last_run_status:
              type: string
              enum: [success, failed, pending]
              example: "success"
            last_run_at:
              type: string
              format: date-time
          required: [id, created_at, updated_at]

    AlertInput:
      type: object
      properties:
        name:
          type: string
          example: "Error Log Spike"
        tissql_query:
          type: string
          example: "SELECT COUNT(*) FROM app_logs WHERE level = 'ERROR' AND timestamp > 'last_5_minutes'"
        frequency_minutes:
          type: integer
          example: 5
        condition:
          type: object
          properties:
            operator:
              type: string
              enum: [>, <, ==, !=, contains, is_empty]
              example: ">"
            value:
              type: string
              example: "0"
        channels:
          type: array
          items:
            $ref: '#/components/schemas/Channel'
      required: [name, tissql_query, frequency_minutes, condition, channels]

    Alert:
      allOf:
        - $ref: '#/components/schemas/AlertInput'
        - type: object
          properties:
            id:
              type: string
              format: uuid
              example: "b2c3d4e5-f6a7-4b3c-8d2e-1f9f8a7b6c5d"
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            current_state:
              type: string
              enum: [ok, triggered]
              example: "ok"
            last_triggered_at:
              type: string
              format: date-time
          required: [id, created_at, updated_at, current_state]

    Channel:
      type: object
      properties:
        type:
          type: string
          enum: [email, slack, webhook]
        target:
          type: string
          description: "Email address, Slack webhook URL, or generic webhook URL."
          example: "ops-alerts@example.com"
      required: [type, target]

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required: [code, message]
    Document:
      type: object
      additionalProperties: true
      description: A flexible JSON-like document.
      example:
        id: "doc123"
        name: "John Doe"
        age: 30
    Schema:
      type: object
      description: Defines the structure of documents in a collection.
      properties:
        fields:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
                enum: [String, Number, Boolean, DateTime, Binary, Object, Array]
              required:
                type: boolean
      example:
        fields:
          - name: "user_id"
            type: "String"
            required: true
          - name: "post_text"
            type: "String"